### ISSUE TITLE
Problem when supplying path to HWE and rad_haplotyper scripts

### ISSUE THREAD

**Issue by jdselwyn** [cbirdlab/fltrVCF#10]
I ran into an issue when I specify the HWE perl script and rad_haplotyper scripts as arguments
```
bash ${fltrVCF} -s ${config} \
  -w ${HWE} \
  -r ${haplotyper} 
```
Basically the issue was when they are echo'd back the second time the script would attempt to run with no arguments. I fixed the error by changing L2061 & L2071 of the `fltrVCF.bash` script to: `HWE_SCRIPT=${OPTARG} #JDS change from RADHAP_SCRIPT=$(${OPTARG})` and `RADHAP_SCRIPT=${OPTARG} #JDS change from RADHAP_SCRIPT=$(${OPTARG})` respectively. That seems to fix the issue. Not sure if there will be knock-on issues with other ways of specifying the script locations.

**Comment by cbird808** [comment]
suggested changes made
